### ISSUE TITLE
No such file or directory: 'kmc'

### ISSUE THREAD

**Issue by lpipes** [sanger-pathogens/saffrontree#16]
```
saffrontree saffrontree_out Results/tree_estimation.fasta 
Traceback (most recent call last):
  File "/home/lenore/.local/bin/saffrontree", line 4, in <module>
    __import__('pkg_resources').run_script('saffrontree==0.1.2', 'saffrontree')
  File "/home/lenore/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/lenore/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1466, in run_script
    exec(script_code, namespace, namespace)
  File "/home/lenore/.local/lib/python3.10/site-packages/saffrontree-0.1.2-py3.10.egg/EGG-INFO/scripts/saffrontree", line 35, in <module>
  File "/home/lenore/.local/lib/python3.10/site-packages/saffrontree-0.1.2-py3.10.egg/saffrontree/SaffronTree.py", line 37, in __init__
  File "/home/lenore/.local/lib/python3.10/site-packages/saffrontree-0.1.2-py3.10.egg/saffrontree/KmcVersionDetect.py", line 11, in __init__
  File "/home/lenore/.local/lib/python3.10/site-packages/saffrontree-0.1.2-py3.10.egg/saffrontree/KmcVersionDetect.py", line 21, in find_version
  File "/home/lenore/Python-3.10.3/Lib/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/lenore/Python-3.10.3/Lib/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/lenore/Python-3.10.3/Lib/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/lenore/Python-3.10.3/Lib/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'kmc'
```

**Comment by andrewjpage** [comment]
Looks like KMC isn't properly installed. Try reinstalling the dependencies and running them (e.g. can you run kmc from the command line).
